### ISSUE TITLE
add registration status to events

### ISSUE THREAD

**Issue by gabeodess** [gabeodess/meetplanner#50]

**Comment by gabeodess** [comment]
@shhanson what are the statuses?  Draft/Open/Closed?

I imagine open and closed events would show up in the search where draft would not.  Would we also want a "Pending" status where the event would show up in the search but not be open for registration?

**Comment by shhanson** [comment]
Statuses are just "Open" and "Closed." Events of either status can show up in the search results, however, only "Open" events allow for registration.
